server:
  port: 9800

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka-1
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:9801/eureka, http://localhost:9802/eureka